---
custom:
  tags:
    default: &tags []
    suse-liberty: ['suse-liberty']
  timeouts:
    long: &timeouts-long 2h

jobs:
- name: validate
  plan:
  - get: validator-src
    trigger: true
    tags: *tags
    timeout: *timeouts-long
  - task: validate
    tags: *tags
    timeout: *timeouts-long
    file: validator-src/ci/validate.yml
    params:
      USERNAME:          {{username}}
      AUTH_URL:          {{auth_url}}
      API_KEY:           {{api_key}}
      DOMAIN:            {{domain}}
      PROJECT:           {{project}}
      DEFAULT_KEY_NAME:  {{default_key_name}}
      NETWORK_ID:        {{network_id}}
      FLOATING_IP:       {{floating_ip}}
      PRIVATE_KEY:       {{private_key}}
      BOOT_FROM_VOLUME:  {{boot_from_volume}}
      INSTANCE_TYPE:     {{instance_type}}
      ROOT_DISK_SIZE:    {{root_disk_size}}
      NTP_SERVER:        {{ntp_server}}

resources:
- name: validator-src
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/cf-openstack-validator
    branch: master
